export const GET_SECTION_REQUEST = "SECTION::GET_SECTION_REQUEST";
export const GET_SECTION_SUCCESS = "SECTION::GET_SECTION_SUCCESS";
export const GET_SECTION_FAILURE = "SECTION::GET_SECTION_FAILURE";